# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 881e2f121635edf25599022d46b24ca1a76528f5cb9968d0cf9d2481ecdea444bfae0eb4963cdbdcaa43e379976e9aa6fb80240e75e39732fc65bc36e8ae96b0
  twitter_key: i4Lr4tNmMhaovbLWsXanfMQMT
  twitter_secret: jDCBXCQLHajdhRVFhcwio54NEe2WEbavclBnu83bYmTxypHjb0
  facebook_key: 
  facebook_secret:
  linked_in_key:
  linked_in_secret:
  private_email: jmscholen+devise@gmail.com
  private_pw: 02jms2007


test:
  secret_key_base: e09f3a06857858c00386f491f4b624f4a0bd42de815d39c83403730c1c66f0e4f543e5a51bd2ed4e29b267905725114bc3eaf880689a6b006e8f1790821fdbcb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
